# For more info on HTTP files go to https://aka.ms/vs/httpfile
@domainName=https://bchousingafswebappmvc.azurewebsites.net
@testDomainName=https://localhost:7158
@subRoute=api
@action=BlobStorage

GET {{domainName}}/{{subRoute}}/{{action}}/Metadata
Content-Type: application/json

{
  "URL":"https://afspocstorage.blob.core.windows.net/file-container/Other/Application_Surrey_2.pdf"
}


####
POST {{testDomainName}}/{{subRoute}}/{{action}}/Metadata
Content-Type: application/json

{
  "URL":"https://afspocstorage.blob.core.windows.net/file-container/Other/Application_Surrey_2.pdf",
  "Metadata": "{\"DocumentName\":\"ApiDocument\",\"SubmitBy\":\"Kai\",\"UserDeclaredType\":\"SAFER\"}"
}



####
POST {{domainName}}/{{subRoute}}/{{action}}/MoveStagingBlob
Content-Type: application/json

{
  "SourceURL":"https://afspocstorage.blob.core.windows.net/staging-container/TestNote.txt",
  "DestinationContainer":"file-container",
  "DestinationFolder": "Other"
}


###
POST {{testDomainName}}/{{subRoute}}/{{action}}/MoveStagingBlob
Content-Type: application/json

{
  "SourceURL":"https://afspocstorage.blob.core.windows.net/file-container/Other/Application_Surrey_2.pdf",
  "DestinationContainer":"file-container",
  "DestinationFolder": "Other"
}


###
GET {{testDomainName}}/{{subRoute}}/{{action}}/Metadata?url=https://afspocstorage.blob.core.windows.net/file-container/Other/Application_Surrey_2.pdf
Content-Type: application/json
