# For more info on HTTP files go to https://aka.ms/vs/httpfile
@domainName=https://bchousingafswebappmvc.azurewebsites.net
@subRoute=api
@action=BlobStorage

GET {{domainName}}/{{subRoute}}/{{action}}/Metadata
Content-Type: application/json

{
  "URL":"https://afspocstorage.blob.core.windows.net/file-container/SAFER-RAP/ApiForAFS.txt"
}


####
POST {{domainName}}/{{subRoute}}/{{action}}/Metadata
Content-Type: application/json

{
  "URL":"https://afspocstorage.blob.core.windows.net/file-container/SAFER-RAP/ApiForAFS.txt",
  "Metadata": "{\"DocumentName\":\"ApiDocument\",\"SubmitBy\":\"Kai\",\"UserDeclaredType\":\"SAFER\"}"
}


####
POST {{domainName}}/{{subRoute}}/{{action}}/MoveStagingBlob/Capture.PNG
Content-Type: application/json

{
  "DestinationContainer":"file-container",
  "DestinationFolder": "Other"
}